services:
  - type: web
    name: agri_pred
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    pythonVersion: 3.11.11
